/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Connect;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LoaiPhong;
import model.PhongHoc;
import model.ThietBi;

/**
 *
 * @author admin
 */
public class LoaiPhongHocScreen extends javax.swing.JFrame {
    private int selectedIndex;
    ArrayList<LoaiPhong> listLP = new ArrayList<>();

    private final Connect db = new Connect();
     static String fileNameLP = "loaiphong.txt";

    private final DefaultTableModel tblModelLoai;

    /**
     * Creates new form TrangChu
     */
    public LoaiPhongHocScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tblModelLoai = (DefaultTableModel) tblLoaiPhong.getModel();

        

        docFileLP(fileNameLP);
        showDataLoaiPhong(listLP, tblModelLoai );

        
    }
    
    public final <T> void showDataLoaiPhong(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for(LoaiPhong t: listLP){
            tblModelLoai.addRow(new Object[]{
                t.getMaLoaiPhong(), t.getLoaiPhong(), t.getKhoa(), t.getCoSo()
            });
        }       
    }
    
    void addLoaiPhong(LoaiPhong lp) {
        listLP.add(lp);
        showDataLoaiPhong(listLP, tblModelLoai);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiPhong = new javax.swing.JTable();
        ThemLoaiPhong = new javax.swing.JButton();
        XemLoaiPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLoaiPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Loại Phòng", "Tên Loại Phòng", "Khoa", "Cơ Sở"
            }
        ));
        jScrollPane1.setViewportView(tblLoaiPhong);

        ThemLoaiPhong.setText("Thêm loại phòng");
        ThemLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemLoaiPhongActionPerformed(evt);
            }
        });

        XemLoaiPhong.setText("Xem Loại phòng");
        XemLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XemLoaiPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(ThemLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(XemLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemLoaiPhong)
                    .addComponent(XemLoaiPhong))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại Phòng Học", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ThemLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemLoaiPhongActionPerformed
        // TODO add your handling code here:
        AddLoaiPhong loaiphongFrm = new AddLoaiPhong(this,
            rootPaneCheckingEnabled);
        loaiphongFrm.setVisible(true);
        luuFile(listLP, fileNameLP);
    }//GEN-LAST:event_ThemLoaiPhongActionPerformed

    private void XemLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XemLoaiPhongActionPerformed
        // TODO add your handling code here:
        int researchIndex = tblLoaiPhong.getSelectedRow();
        if (researchIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Chọn loại phòng học cần xem!");
        } else if (listLP.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Không có thông tin cần xem!");
        } else {      
            TrangChuAdmin home = new TrangChuAdmin();
            home.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_XemLoaiPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiPhongHocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiPhongHocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiPhongHocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiPhongHocScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiPhongHocScreen().setVisible(true);
            }
        });
    }
    public void luuFile(ArrayList T, String fileName) {
        try {
            db.writeToFile(T, fileName);
            System.out.println("Luu file thanh cong");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    public void docFileLP(String fileName) {
        try {
            listLP = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" Doc file LP");
        } catch (Exception ex) {
            System.out.println("Khong doc duoc file");
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThemLoaiPhong;
    private javax.swing.JButton XemLoaiPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblLoaiPhong;
    // End of variables declaration//GEN-END:variables



   

    

    

    



    

    
}
