/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Connect;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LoaiPhong;
import model.PhongHoc;
import model.ThietBi;

/**
 *
 * @author admin
 */
public class TrangChuGiangVien extends javax.swing.JFrame {
    private int selectedIndex;
    ArrayList<LoaiPhong> listLP = new ArrayList<>();
    ArrayList<PhongHoc> listPH = new ArrayList<>();
    ArrayList<ThietBi> listTB = new ArrayList<>();
    private final Connect db = new Connect();
   
    static String fileNamePH = "phonghoc.txt";
    static String fileNameTB = "thietbi.txt";

    private final DefaultTableModel tblModelPhong;
    private final DefaultTableModel tblModelThiet;
    /**
     * Creates new form TrangChu
     */
    public TrangChuGiangVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        tblModelPhong = (DefaultTableModel) tblPhongHoc.getModel();
        tblModelThiet = (DefaultTableModel) tblThietBi.getModel();
        
        docFilePH(fileNamePH);
        showDataPhongHoc(listPH,tblModelPhong );
        
        
        //fakedata();
        docFileTB(fileNameTB);
        showDataThietBi(listTB, tblModelThiet );
        
    }
    
    
    public final <T> void showDataPhongHoc(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for(PhongHoc t: listPH){
            tblModelPhong.addRow(new Object[]{
                t.getMaPhong(),t.getTenPhong(), t.getSoLuongMay(), t.getTinhTrang(), t.getLoaiPhong(), t.getCoSo()
            });
        }       
    }
    public final <T> void showDataThietBi(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for(ThietBi t: listTB){
            tblModelThiet.addRow(new Object[]{
                t.getMaTB(),t.getTenTB(), t.getLoaiTB(), t.getSoHoatDong(), t.getSoLoi(), t.getNamSX(), t.getTenPhong()
            });
        }       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhongHoc = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThietBi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TimKiemNgay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSoHD = new javax.swing.JTextField();
        Load = new javax.swing.JButton();
        txtNam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoLoi = new javax.swing.JTextField();
        boxLoaiTB = new javax.swing.JComboBox<>();
        boxTenPhong = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPhongHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phòng", "Tên phòng học", "Số lượng máy", "Tình trạng", "Loại Phòng", "Cơ sở"
            }
        ));
        jScrollPane2.setViewportView(tblPhongHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phòng Học", jPanel2);

        tblThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thiết bị", "Tên thiết bị", "Loại thiết bị", "Số hoạt động", "Số lỗi", "Năm SX", "Tên phòng"
            }
        ));
        jScrollPane3.setViewportView(tblThietBi);

        jLabel1.setText("Chọn năm:");

        TimKiemNgay.setText("Tìm kiếm");
        TimKiemNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiemNgayActionPerformed(evt);
            }
        });

        jLabel2.setText("Tổng số thiết bị hđ:");

        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        txtNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamActionPerformed(evt);
            }
        });

        jLabel3.setText("Loại thiết bị:");

        jLabel4.setText("Tổng số thiết bị lỗi:");

        boxLoaiTB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Màn hình", "Case máy tính", "Chuột", "Bàn phím" }));

        boxTenPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "701", "702", "703", "801", "802" }));
        boxTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTenPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(boxLoaiTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TimKiemNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(57, 57, 57))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSoLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(boxTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TimKiemNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Load))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(boxLoaiTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoLoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thiết Bị", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamActionPerformed

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
        docFileTB(fileNameTB);
        showDataThietBi(listTB, tblModelThiet);
        /*int removeIndex = tblThietBi.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                "Chọn Ca cần xóa!");
        } else if (listTB.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                "Không có thông tin!");
        } else {
            listTB.remove(removeIndex);
            showDataPhongHoc(listTB, tblModelThiet);
        }
        luuFile(listTB, fileNameTB);*/
    }//GEN-LAST:event_LoadActionPerformed

    private void TimKiemNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiemNgayActionPerformed
        String  loaiThietBi;
        int nam;
        int soLuongHoatDong = 0;
        int soLuongLoi = 0;
        boolean check = false;
        nam = Integer.valueOf(txtNam.getText());
        loaiThietBi = boxLoaiTB.getSelectedItem().toString();

        tblModelThiet.setRowCount(0);
        for (ThietBi tb : listTB) {
            if ( (nam == tb.getNamSX()) && (loaiThietBi.equals(tb.getLoaiTB())) ) {
                tblModelThiet.addRow(new Object[]{
                    tb.getMaTB(),tb.getTenTB(), tb.getLoaiTB(), tb.getSoHoatDong(), tb.getSoLoi(), tb.getNamSX(), tb.getTenPhong()
                });
                soLuongHoatDong += tb.getSoHoatDong();
                soLuongLoi += tb.getSoLoi();
                check = true;
            }
        }
        txtSoHD.setText(Integer.toString(soLuongHoatDong));
        txtSoLoi.setText(Integer.toString(soLuongLoi));

        if (check == false) {
            JOptionPane.showMessageDialog(rootPane
                , "Năm không đúng hoặc không có loại thiết bị đó");
            showDataThietBi(listTB, tblModelThiet);
        }
    }//GEN-LAST:event_TimKiemNgayActionPerformed

    private void boxTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTenPhongActionPerformed
        // TODO add your handling code here:
        int tenPhong ;
        boolean check = false;
        tenPhong = Integer.valueOf(boxTenPhong.getSelectedItem().toString());
        tblModelThiet.setRowCount(0);
        for (ThietBi tb : listTB) {
            if ( (tenPhong == tb.getTenPhong()) ) {
                tblModelThiet.addRow(new Object[]{
                    tb.getMaTB(),tb.getTenTB(), tb.getLoaiTB(), tb.getSoHoatDong(), tb.getSoLoi(), tb.getNamSX(), tb.getTenPhong()
                });
                check = true;
            }
        }

        if (check == false) {
            JOptionPane.showMessageDialog(rootPane
                , "Không có tên phòng trong danh sach");
            showDataThietBi(listTB, tblModelThiet);
        }
    }//GEN-LAST:event_boxTenPhongActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuGiangVien().setVisible(true);
            }
        });
    }
    public void luuFile(ArrayList T, String fileName) {
        try {
            db.writeToFile(T, fileName);
            System.out.println("Luu file thanh cong");
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    public void docFileLP(String fileName) {
        try {
            listLP = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" Doc file LP");
        } catch (Exception ex) {
            System.out.println("Khong doc duoc file");
        }
    }
    public void docFilePH(String fileName) {
        try {
            listPH = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" Doc file PH");
        } catch (Exception ex) {
            System.out.println("Khong doc duoc file");
        }
    }
    public void docFileTB(String fileName) {
        try {
            listTB = (ArrayList) db.readDataFromFile(fileName);
            System.out.println(" Doc file TB");
        } catch (Exception ex) {
            System.out.println("Khong doc duoc file");
        }
    }
    public void writeFileLP(){
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        try{
             fos = new FileOutputStream("LoaiPhong.txt");
             oos = new ObjectOutputStream(fos);
            oos.writeObject(listLP);
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try{
                oos.close();
                fos.close();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
    
    public void readFileLP(){
        FileInputStream fis = null;
        ObjectInputStream ois = null;
        try{
            fis = new FileInputStream("LoaiPhong.txt");
            ois = new ObjectInputStream(fis);
            listLP =  (ArrayList<LoaiPhong>)ois.readObject();
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try{
                if(ois != null && fis != null){
                    ois.close();
                    fis.close();
                }
                
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JButton TimKiemNgay;
    private javax.swing.JComboBox<String> boxLoaiTB;
    private javax.swing.JComboBox<String> boxTenPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPhongHoc;
    private javax.swing.JTable tblThietBi;
    private javax.swing.JTextField txtNam;
    private javax.swing.JTextField txtSoHD;
    private javax.swing.JTextField txtSoLoi;
    // End of variables declaration//GEN-END:variables

    

    

    



    

    
}
